name: Go

on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt update && sudo apt install -y libsnmp-dev libc-dev build-essential libnetfilter-queue-devã€€libnfnetlink-dev
      - name: Set up Go 1.14.7
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14.7
        id: go
      - name: run go get
        run: go get
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.26
          args: --enable=golint,gosec,prealloc,gocognit
